server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oath2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-url: "http://127.0.0.1:8082/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-url: "http://127.0.0.1:8082/authorized"
            scope: api.read
            client-name: api-client-authorization-code
          provider:
            spring:
              issuer-url: http://auth-server:9000
